### ISSUE TITLE
create workflow for latex documentation

### ISSUE THREAD

**Issue by philippabele** [philippabele/pythonic-api-design#31]
Create a Github Actions Workflow in order to automatically build a documentation for the entire project.

This example could help you to set it up

https://github.com/philippabele/developers-guide-to-linux/blob/main/.github/workflows/compile-latex.yml

**Comment by HenrikFrtz** [comment]
@philippabele 

I'm testing this one and I face an issue. Latex throws an error, because the images can't be loaded. I added a stage in compile-latex.yml to copy all images to the graphics folder in 00_latex_template. They are correctly copied there, I've tested this.
Do you know how to include the images in latex, which I use in my .MD files?

Branch: feature/latex-documentation

**Comment by philippabele** [comment]
@HenrikFrtz Maybe this site https://de.overleaf.com/learn/how-to/Writing_Markdown_in_LaTeX_Documents#Images_and_Referencing provides helpful details.

**Comment by HenrikFrtz** [comment]
Finally I am able to a Latex document containing images. They must be copied in the main directory in GitHub Actions.
I excluded the main README.md file, because I think that the Python badges should be included in the Latex PDF.

After inspecting the repo [Developers guide to Linux](https://github.com/philippabele/developers-guide-to-linux](https://github.com/philippabele/developers-guide-to-linux/blob/main/.github/workflows/compile-latex.yml) I understand how to structure my project and name the Markdown files. I'll rename them in a new PR, as soon as the three open issues are merged.
