### ISSUE TITLE
Connect a postgreSQL db with fastAPI

### ISSUE THREAD

**Issue by philippabele** [philippabele/pythonic-api-design#8]
Create a simple model and make CRUD operations available at the API.

Persist the data at a postgreSQL db.

- [Hint1](https://testdriven.io/blog/fastapi-crud/#post-route)
- [Hint2](https://fastapi.tiangolo.com/tutorial/sql-databases/#create-model-attributescolumns)

**Comment by HenrikFrtz** [comment]
@philippabele: This issue is nearly done, but I'm facing a problem regarding Pytest. Everything works fine in Docker, tried Swagger as well.
But the pytest in docker fails every time, because the python files cannot be imported. I have to write the following:
![grafik](https://user-images.githubusercontent.com/72461944/156985267-042ed3fb-d98c-4be3-a14f-13ee2537d774.png)

But then, libs in the main.py file cannot be imported. 

I really don't know what to do, i set up everything like in the tutorial and spent days with this issue. I would really appreciate a hint from your site. Thanks!

**Comment by HenrikFrtz** [comment]
Have a look into the feature branch, I pushed my recent changes and this branch is up to date.

**Comment by philippabele** [comment]
@HenrikFrtz, no problem. Let's fix this issue step by step.

First, about which feature branch are you writing about?

Second, in order to start the project the right way an up-to-date readme.md is vital. Please double check this.

**Comment by HenrikFrtz** [comment]
@philippabele I've updated the readme.MD so you can now use Docker.

I'm talking about this branch: feature/sql_database


The application is running correctly in Docker, but Pytest fails. This is due to the import names/folders. I have to provide different folders to get both to work, pytest and the 'real' application.


![grafik](https://user-images.githubusercontent.com/72461944/169788047-c7b67270-2809-448b-85df-fc776c79bd28.png)

**Comment by HenrikFrtz** [comment]
Merged into development.
